### ISSUE TITLE
NameIDPolicy not populating // may be due to Metadata not updating?

### ISSUE THREAD

**Issue by dustinbrisebois** [catalyst/moodle-auth_saml2#246] opened 2018-04-06 03:54 UTC
Have a case where the metadata.php appears to have been created once, however no matter what is changed is not being updated by the plugin. 

This is occuring on latest 2018032900 release.

It does not matter if the setting to update via scheduled task is enabled or not, no setting was found that would enable the metadata to update. Even using "test code" -- nothing showed that the metadata xml file in the data folder was being updated by the plugin once it was generated.

**Comment by dustinbrisebois** [comment] 2018-04-06 03:55
** will attempt to find where the issue is occuring in plugin and/or get system error logs to track problem

**Comment by dustinbrisebois** [comment] 2018-04-06 05:00
so - by design it appears that if you do:

metadata.php?regenerate=true (AND if you are a site admin) it will regenerate however -- this is undocumented and SHOULD update automatically if a setting has been changed.

**Comment by dustinbrisebois** [comment] 2018-04-06 05:11
In addition -- the function auth_saml2_get_sp_metadata appears to only be called when the metadata.php file is called manually -- nothing to do with the task itself. The task to refresh the file appears to be not only indepdent but call a different set of parameters and may possible generate a different style of metadata file.

**Comment by brendanheywood** [comment] 2020-02-21 13:39
Duplicate of https://github.com/catalyst/moodle-auth_saml2/issues/228 and now fixed

**Closed by brendanheywood** 2020-02-21 13:39 UTC
Labels: bug
