### ISSUE TITLE
certificate creation fails 

### ISSUE THREAD

**Issue by blenke** [catalyst/moodle-auth_saml2#12] opened 2016-07-07 11:21 UTC
I'm trying to configure SAML2 . I would like to regenerate a certificate but this seems fails without specific information, error message is:

Creation of Private Certificate failed.

I place a .crt file in the \sitedata\saml2 folder on the server. This is read correctly in the Regenerate Private Key form and in View SP Certificate it also shows the correct certificate information.

I need to create an xml for our SSO system. At this point it fails due to the missing .pem file (even though I also copied this to the same \saml2 folder. It gives an odd path in the error message after I click 'View Service Provider Metadata':

Exception - Could not find private key file [[dataroot]/saml2/[dataroot]/saml2/myserver.mydomain.nl.pem], which is needed to sign the metadata 

Server: Windows 2012 R2
PHP 5.6
Moodle 3.0
The php open ssl plugin is installed

**Comment by brendanheywood** [comment] 2016-07-07 14:21
It's designed to generate everything automatically, you don't need to do anything and it will generate a cert pair for you. If you want to customize the content of the cert then use the GUI form, and then click the regenerate button. If you really want to generate the cert pair manually (ie you've been given a set from somewhere else) then place both files into the right place on top of the autogenerated ones with the right file name, and then unset the write bit so they can't be deleted. It isn't designed to be given one half of the pair and to try and generate the other half.

If the auto cert pair creation is failing completely, ie if you just delete the entire /dataroot/saml2 directory and start again, then I guess there is some part of openssl libs which aren't loaded. You'd have to dig around setup.php line 85 and see what's going on.

Is the dataroot/saml2 part of the path actually duplicated twice in the error? That would be odd

**Comment by blenke** [comment] 2016-07-07 14:28
The regenerate does not work. In the mean time I figured out that the openssl does not work properly. I made a test page outside moodle to see if it runs the openssl_pkey_new() but this fails if I run it from the web site. If I run it from the command line on the web server with php.exe -a openssl.php then it works fine. I will try to get this running first before I continue with saml2, I assume the openssl needs to work before I can continue.

**Comment by blenke** [comment] 2016-07-11 08:09
The problem with the cert pair creation is fixed, this was due to a missing folder name in the windows search path to the openssl folder which unfortunately requires a server restart. 
The problem with the SP metadata is not fixed , it is still giving me the odd error message with the multiple [dataroot] name:
Exception - Could not find private key file [[dataroot]/saml2/[dataroot]/saml2/myserver.mydomain.pem], which is needed to sign the metadata
The actual local path is d:\websites\moodletestdata\saml2 and contains the .crt and .pem files.

**Comment by blenke** [comment] 2016-07-11 09:49
I now changed in \auth\saml2\auth.php the following lines:
        $this->certpem = $this->certdir . $this->spname . '.pem';
        $this->certcrt = $this->certdir . $this->spname . '.crt';
To:		
        $this->certpem = $this->spname . '.pem';
        $this->certcrt = $this->spname . '.crt';

apparently the spname already contains the full path here. Adding the certdir will add the path twice.
The xml is now shown. Perhaps a windows specific issue ?

**Comment by brendanheywood** [comment] 2016-07-11 11:07
Yeah that feels like it's getting closer to the root cause, can you please have a poke around these lines here:

https://github.com/CatalystIT-AU/moodle-auth_saml2/blob/master/auth.php#L60-L61

and see what each var's value is, $this->spname should be just 'myserver.mydomain', and I suspect there is some weird url parsing with the \ vs / slashes in the windows paths and so it is returning more than it should. Can you put together a pull request?

**Comment by blenke** [comment] 2016-07-11 15:45
I'm not an experienced php programmer so its a bit hard to get through.

the $this->certdir contains d:\websites\moodletestdata
so the / and \ are mixed up after appending the pem folder and file name. However if I put a fixed path in the $this->certpem like d:/websites/moodletestdata or with \ then it still tries to add the dataroot in front of the file name. So it looks like this is also added someplace else. Without dataroot it seems to work fine. 

Changing the \\ to / in the $CFG->dataroot in the config.php of moodle doesn't help.

**Comment by brendanheywood** [comment] 2016-07-12 06:38
What doesn $this->spname contains just after this line has executued?

```
auth.php:60    $this->spname = $mdl->get_host();
```

**Comment by blenke** [comment] 2016-07-12 07:00
That contains only the site name , myserver.mydomain.nl so it does not contain the path (as expected I assume)
certdir=D:\websites\moodletestdata/saml2/
certpem=D:\websites\moodletestdata/saml2/myserver.mydomain.nl.pem
certcrt=D:\websites\moodletestdata/saml2/myserver.mydomain.nl.crt

This is also working:
if (file_exists($this->certpem)) { 
		echo 'pem found';
	}
So I assume that the problem is created at another point in the code.
I can only make it work by leaving out the certdir from certpem and certcrt.

**Comment by brendanheywood** [comment] 2016-07-14 03:17
Hmm, I think the two cert paths should always be relative to the certdir, and this is a bug everywhere but just happens to work in unix. So I think this is a proper bug, will look into it...

**Comment by danish160** [comment] 2016-07-14 06:53
HI Brendan

I am getting the same error. 

In my moodledata/saml2, there is not .crt file. 

I tried generating it through UI (Regenerate certificate button) but it throws the error "Creation of Private Certificate failed.". 

Is there any work around for this, I mean can I put some hardcoded values somewhere to make it work ?

Any help will be appreciated.

Moodle version: 2.9
PHP: 5.4.45

Thanks, 
Danish

**Comment by blenke** [comment] 2016-07-14 07:08
If it is the same problem that I had then you can change the auth.php file. At first I had problems with my openssl configuration so you need to make sure this is working properly from php. In my case the problem on a Windows server was that it needed a reboot because the search path had changed and this is only copied for the system account after a reboot.

I changed in \auth\saml2\auth.php the following lines (line 62):
 $this->certpem = $this->certdir . $this->spname . '.pem';
 $this->certcrt = $this->certdir . $this->spname . '.crt';
 To:

 $this->certpem = $this->spname . '.pem';
 $this->certcrt = $this->spname . '.crt';

**Comment by danish160** [comment] 2016-07-14 07:21
I am not using OpenSSL. It is a test instance of moodle, I am trying to implement a single sign on functionality from an ASP.Net application to moodle. So I guess my problem is not exactly same as yours. 

I am just stuck at the certificate generation step.

**Comment by brendanheywood** [comment] 2016-07-14 07:29
This is not ssl in terms of https / TLS, it's the internal php libraries that moodle uses to decrypt the assertions, it needs to be installed. In #13 I'll add some checking at install time to warn / error if it's not available.

**Comment by GavinNelson** [comment] 2017-08-30 16:03
I'm also getting this issue (error message with multiple [datadir]/saml2 parts in path) on a windows server when trying to view the SP metadata.

If I remove the "$this->certdir . " parts in auth.php, I get a permision denied error where it seems to be trying to write inside wwwroot.
If I then re-insert the "$this->certdir . " parts then the SP metadata loads successfully, but seems to reset after some time requiring for the code to be changed again to access it.

**Comment by brendanheywood** [comment] 2017-08-30 23:31
> If I remove the "$this->certdir . " parts in auth.php, I get a permision denied error where it seems to be trying to write inside wwwroot.

I can't really help with this as I don't have any windows env's for testing. If anyone wants commercial support and can provide a windows environment where this fails for testing that would be ideal.

simply put the certdir needs to be set, and it needs to be the /saml dir inside your moodle data dir. I suspect this issue is actually confusing a couple different issues windows issues depending on different setups, but it will boil down to either the fully qualified certdir path not being right, or an implicit path based on the current working directory not being right, or it's unrelated and to do with the ssl libs not being available. The first 2 issues you should be able to debug fairly easily with a few debug lines somewhere, either the directory string is not getting made correctly, or encoded right or something weird like that.

I would also suggest you play with setting the 'basedir' directory in config.php to something explicit, for instance it could be the datadir . '/saml' directory and then the 'certdir' could just be '' so they are the same.

**Comment by roperto** [comment] 2018-03-08 05:14
I am closing this one as we cannot reproduce and SAML2 had many updates since then.

Please reopen or create a new issue if this is affecting you.

**Closed by roperto** 2018-03-08 05:14 UTC
Labels: bug
