### ISSUE TITLE
BadRequest-missing target parameter

### ISSUE THREAD

**Issue by hjiangdesign** [catalyst/moodle-auth_saml2#303] opened 2018-12-13 23:59 UTC
I have installed SAML2 plugin and integrated with OKTA for SSO, however, I am getting the following error message once I authenticate with OKTA successfully and OKTA pass the page to moodle 
The error message: 
**Exception - BADREQUEST('%REASON%' => 'Missing TARGET parameter.')**

any idea why? any help would appreciate 
![image 13-12-18 at 1 33 pm](https://user-images.githubusercontent.com/38970368/49972035-9ed00900-ff84-11e8-8c12-ae5e36375d09.jpg)
Here is the Saml 2 setting. 
![saml2 setting](https://user-images.githubusercontent.com/38970368/49973494-74347f00-ff89-11e8-9754-0c3f4593c6c0.png)

**Comment by dkleto** [comment] 2018-12-19 01:43
Hi @hjiangdesign,

There are a few things you can try that might help.

If you haven't already, take a look at the OKTA-specific section of the plugin readme. There are some OKTA configuration options which might be worth double-checking. One particular thing to check is that the URL paths listed there are correct in the OKTA config - the error you've encountered is usually only thrown by the SAML1 service provider code, so make sure these are pointing at the correct saml2 paths (e.g. saml2-acs.php rather than saml1-acs.php).

If that doesn't work, try going through the steps listed in the "Debugging" section of the readme. Enabling debugging in the saml2 config as well as turning the Moodle-wide debugging level up to DEVELOPER may reveal some additional errors which could provide some clues about what's going on.

**Comment by hjiangdesign** [comment] 2018-12-19 22:22
Hi @dkleto 
You are a genius. yes, that fixes the issue. but when we implement that, there is another issue happened. The error message is: 
You have logged in successfully but we could not find your 'user.login' attribute to associate you to an account in Moodle.
![error](https://user-images.githubusercontent.com/38970368/50251590-7cccff80-0438-11e9-9fbf-3ac1790c0ff2.png)

Any suggestion? did we miss something when we do the configuration?
Looking forward to your reply.
Thanks again.

**Comment by danmarsden** [comment] 2019-10-04 01:58
as this appears to be configuration specific and not a bug with the plugin I'm closing this one off. If you're still having issues you might like to ask for help in the moodle community forums - thanks!

**Closed by danmarsden** 2019-10-04 01:58 UTC

**Comment by KernelPan1k** [comment] 2021-05-12 14:13
Hi,

if anyone is passing here, who like me doesn't know about saml and comes across this message:

" You have logged in successfully but we could not find your 'user.login' attribute to associate you to an account in Moodle."

 here's how I solved the problem after two hours of research.

The XML did not have an Attribute node so I chose the following options:

- Expose NameID as attribute  => Yes
- Mapping IdP => nameid

It's simple when you know the saml I guess

**Comment by golapdk** [comment] 2022-10-19 14:57
Check the ACS URL in IDP. its may be point to [simplesaml/module.php/saml/sp/saml1-acs.php/*].

Please ask the IDP to point  [simplesaml/module.php/saml/sp/saml2-acs.php/*]

It will resove the issue.

<img width="957" alt="1" src="https://user-images.githubusercontent.com/10330560/196727210-a0293658-a571-49be-b954-e77b0c8d26e7.png">
