### ISSUE TITLE
Test Settings page broken.

### ISSUE THREAD

**Issue by ertborTek** [catalyst/moodle-auth_saml2#591] opened 2021-07-22 19:48 UTC
When accessing the _Test setting_ page (which invokes **tester.php**), an exception is thrown.  

> Exception - Call to a member function set_context() on null

> Debug:
> Error code: generalexceptionmessage

> Stack trace:
> * line 36 of /auth/saml2/tester.php: Error thrown
> * line 1063 of /auth/saml2/classes/auth.php: call to include()
> * line 72 of /auth/test_settings.php: call to auth_saml2\auth->test_settings()

From the Apache error log: 

> PHP Notice:  Undefined variable: PAGE in .../moodle/auth/saml2/tester.php on line 36
> Default exception handler: Exception - Call to a member function set_context() on null

This is with version **2021062900** on Moodle version **2021051701.01**.
PHP: **7.3.27**

The issue (tester.php:36) seems to be PAGE is `NULL`, which it shouldn't be because `../../config.php` is required and requires `lib/setup.php`, which sets `$PAGE` and makes it global.

The only way I've found to get around this is to declare `$PAGE` global within tester.php, like `global $PAGE;` before line 36.

Note: this wouldn't have been in issue in version < 2021062900 since `$PAGE->set_context(context_system::instance());` et al. where recently added.

**Comment by danmarsden** [comment] 2021-07-23 04:15
Thansk @ertborTek , @kabalin this looks like a regression from 9e282540a8ea819bdb547b14200a2a9a02334d96 - any chance you could take a closer look at that?

**Comment by kabalin** [comment] 2021-09-17 16:15
Regression indeed, going to refator to get rid of tester.php completely, all it is doing is displaying the form, which can be embedded directly into `auth::test_settings`.

**Comment by danmarsden** [comment] 2022-03-14 22:49
this was fixed - closing this off.

**Closed by danmarsden** 2022-03-14 22:49 UTC
