### ISSUE TITLE
Error database get_record() message when testing SAML2 plug-in

### ISSUE THREAD

**Issue by StevePoling** [catalyst/moodle-auth_saml2#169] opened 2017-12-08 20:38 UTC
I installed SAML2 plug-in onto Moodle v2.7.20 (yes, i know it's old.). All seems OK. Manage Authentication display shows SAML2 and links for "settings" and "test settings". I click test settings, and I get a screen that shows "You are not logged in: Login". (I presume I should click on Login.)

However immediately below this appears an error message: 

Fatal error: Call to a member function get_record() on a non-object in /opt/bitnami/apps/moodle/htdocs/auth/saml2/classes/store.php on line 129

The code in question references a variable named $DB. I presume this should be initialized to be an object with databasey methods like get_record(), get_records_sql(), and update_record(). However, it seems $DB hasn't been initialized. Strangely, I looked into the database and saw it has a mdl_auth_samltwo_kvstore table with what appears to be the correct values stored therein. So, something else was able to access the database. 

This makes me think I've goofed up the install and failed to connect the database to the SAML2 plug-in. I would appreciate a nudge in the right direction to see what to check: who's calling set()? who might be setting/resetting $DB?

Thanks in advance,

steve

**Comment by brendanheywood** [comment] 2017-12-10 22:30
That feel likes a code error, but that also doesn't make sense because that's mission critical code that's getting hammered constantly. Are you able to reproduce and give me a full stack trace?

**Comment by StevePoling** [comment] 2017-12-15 07:25
I've had a devil of a time getting a stack trace. Seems the place where the error occurs isn't amenable to opening files, or writing looong strings to error_log. (and I am pretty ignorant about PHP). 

So, I've been sprinkling in this code:

{code}

if ($DB == NULL) {
        $duh = print_r(debug_backtrace(),true);
        \error_log($duh);
}

{code}

SimpleSAML_Session::__destruct() invokes $this->save(). When it does so, global $DB is null. Now, in C++ I'd suggest that something is deleting $DB before deleting SimpleSAML_Session via __destructor().

Can you describe the life-cycle of SimpleSAML_Session objects? Who creates and deletes them? What's the last time your code touches one? (So I can ascertain whether global $DB is non-null at some point and becomes nulled at a later point?)

(I see that the database is getting some session info, so some kinda database access object is getting initialized by someone.)

If you still want to see the stack trace I'll show you what I've been collecting. (If you've got debugging suggestions better than the code I showed above, please advise.)

**Comment by StevePoling** [comment] 2017-12-15 16:00
Now, I understand the problem better. The SimpleSAML_Session object is being instantiated twice. The first time it is instantiated with global $DB properly initialized. The 2nd time it is instantiated with $DB set to null. My question now turns to why 2 such objects should be instantiated? And who is doing the instantiating... This is consistent with what I'm seeing. The 1st instance is storing the stuff I'm seeing in the database. The 2nd instance is going off the rails.

**Comment by StevePoling** [comment] 2017-12-16 03:48
When the SimpleSAML_Session object is released from the system, it calls flush(). This in turn calls a method that stores any changes to the object. Any time prior to calling flush() the $DB global is non-null. However, when flush() gets called, $DB is accessed, but is in a null state. It feels like a race condition between the $DB's destructor and SimpleSAML_Session's destructor. I'm pretty ignorant about the plumbing, but it feels like garbage collection is invoking both destructors, but doing so in the wrong order. Why does nobody else see this? I suppose everyone else has the good sense to run a newer version of Moodle. Or everyone else's garbage collection hasn't been knocked off the happy-path in just the wrong way that changes the order of destructor invocations. 

I could be full of it, but this is what I think I've been seeing yesterday and today. My fix was to go into the store() routine test for $DB==null before touching it. I don't know whether this was a bad thing or not. It got the error message to go away, but my SSO still isn't working...

If I find anything interesting, I'll let you know.

**Comment by brendanheywood** [comment] 2017-12-17 23:09
hi @StevePoling my first bit of advice would be to setup a proper debugger and then you can just step through the code interactively in your ide and save all the guess work. ie using xdebug:

https://docs.moodle.org/34/en/Debugging#See_also

You can also ramp up the debug level in moodle itself, but depending on the code moodle may not have bootstrapped yet so this won't take effect:

https://docs.moodle.org/33/en/Debugging#Debug_messages_and_display_debug_messages

Also what environment are you running php under? I doubt the moodle version matters that much, but the php version and the way it is being invoked will me more important (ie os, apache, nginx / fpm etc?)

**Comment by StevePoling** [comment] 2017-12-18 03:06
Brendan,

You are so spot on about setting up a proper debugging/development
environment. I'm reduced to doing old-school tricks I learned building
embedded systems. (I got started with punched cards in the '70s, so I have
an unrealistic tolerance for bad developer-experience.) I feel like a
complete idiot. I've given your contact info to Ken Andrus (who owns the
company that I'm helping), and asked him to try to hire you as a
consultant. If the stars align, I'd be much obliged if you did a little
hand-holding as I learn where the ground is (i.e. fit the fundamental
elements of the environment to what I know) and grok 21st century PHP
development. Meanwhile, i'll study the two links you provided and try not
to sound too ignorant when I pepper you with questions.

I've got an AWS EC2 instance running Linux and PHP 5.5.30. I'm doing
everything via terminal/command-line makes for slow going. I'm using Chrome
and a 3rd party is providing the IdP. I'm thinking I need to either set up
my own IdP so I can see both sides of the conversation.

After I get the SSO sorted, I want to upgrade ALL the tooling to
latest-greatest versions. And a scheme to apply all minor-version updates
with minimal human involvement.


Thanks in advance,

steve

**Comment by brendanheywood** [comment] 2017-12-18 03:18
If you want either consultancy or even look to fully host with us (we have fully automated deploys and upgrades and much more as part of our services) then please fill out this form:

https://www.catalyst-au.net/content/contact-us

If you want to setup a local idp this is quite trivial and you can follow your nose here:

https://simplesamlphp.org/docs/stable/simplesamlphp-idp

The only thing I do differently is this step:

https://simplesamlphp.org/docs/stable/simplesamlphp-idp#section_7

which in dev I setup using xml urls pointing back to the moodle sp instead of php arrays:

```
'metadata.sources' => array(
    array('type' => 'xml', 'url' => 'http://moodle.local/auth/saml2/sp/metadata.php'),
),
```

One caveat is that every idp has a different flavor, so you might get it working locally and still not working with your prod idp.

**Comment by StevePoling** [comment] 2017-12-18 03:49
Thank you, sir. If you're ever in Grand Rapids, MI, or I'm down under, I'll
buy a round of your favorite beverage.

smiles and cheers,

steve

**Comment by StevePoling** [comment] 2017-12-18 19:23
Hey, my boss wants to give you a jingle, can you PM me your contact info?

**Comment by brendanheywood** [comment] 2017-12-19 00:38
Given the timezones delta to Sydney and the proximity to Christmas leave it's probably better to fire off some questions via email: brendan@catalyst-au.net Also I'm flat out til the break and then back on 8th Jan. I can probably answer quick questions but if we need dev work we'll schedule that for some time in the new year.

**Comment by StevePoling** [comment] 2017-12-19 06:59
Don't worry about timezones. I'll adjust to Sydney time. My daughter lives
in Singapore and Banalore, India so I am accustomed to big time deltas.
I've just got one big family event on Christmas Eve, so I can adjust to fit
your sched.

**Comment by sam-moodle** [comment] 2018-01-05 23:35
@StevePoling, I ran into the same/similar issue when trying to set up an IDP-initiated SSO only scenario. See my issue here https://github.com/catalyst/moodle-auth_saml2/issues/105. When I dug into I was finding that $DB was null when the session store tried to do whatever it was trying to do on shutdown. I wasn't able to find a good solution so I wrote a Redis-backed session store class instead. See https://github.com/catalyst/moodle-auth_saml2/blob/MOODLE_33PLUS/classes/redis_store.php That has worked great, but it obviously requires that you have a Redis instance available.

**Comment by danmarsden** [comment] 2018-03-07 23:19
we've just run into this same issue on a 3.1 site running PHP 5.5 too - We might need to change the "supported" php versions of the plugin or release different git branches for the supported versions.

**Comment by danmarsden** [comment] 2018-03-07 23:21
- I suspect upgrading to php 5.6 might fix this

**Comment by roperto** [comment] 2018-03-09 04:46
This has been fixed in d139161a2093e6644b048f2e3b7dda4ad4622c1d

It seemed related to caching, when running PHPMD -- see #213 -- it warned about the undeclared variable and it has been fixed.

**Closed by roperto** 2018-03-09 04:46 UTC

**Comment by danmarsden** [comment] 2018-03-09 05:38
sweet! - I'll see if it works on the site I was testing on and will let you know.

**Comment by roperto** [comment] 2018-03-09 05:58
@danmarsden 

Let me know, but Monday it's holiday here :-)

By the way, this is PHP 5.5 with Moodle 3.1 passing: https://travis-ci.org/catalyst/moodle-auth_saml2/jobs/351158226

**Comment by danmarsden** [comment] 2018-03-09 06:00
Yep - just deployed, no more 500 error and it's working as expected - nice work thanks!
