### ISSUE TITLE
saml2 (in Totara) w/ Custom Fields can generate contextid missing errors

### ISSUE THREAD

**Issue by dustinbrisebois** [catalyst/moodle-auth_saml2#103] opened 2017-04-26 23:12 UTC
add (line 277): $PAGE (to global list)

add below $auth->requireAuth(); on line 283:

        $context = context_system::instance();
        $PAGE->set_context($context);

this will set the site context for login workflow (in some instances of custom fields with drop down menu items).

**Comment by brendanheywood** [comment] 2017-04-26 23:31
thanks @dustinbrisebois can you please make a pull request?

**Comment by roperto** [comment] 2017-08-17 07:12
I am reopening this issue as we had to revert the commit due to issue #117 

Basically this fix was setting the context of a page as system after login with the IDP which made many components in the course page to not work. It probably affected other pages not in the system context as well. After the `require_login()` in `course/view.php` we need to make sure the context is the correct course context.

If you can provide more information on how to replicate this particular issue we can try to find another solution, preferably with Moodle as we cannot automate tests with Totara in Travis.

Thank you,

Daneil

**Comment by roperto** [comment] 2018-03-08 05:35
I am closing this one as we had several updates to improve its compatibility with Totara and I could not reproduce that one.

Please reopen it if you can still reproduce it.

**Closed by roperto** 2018-03-08 05:35 UTC
Labels: bug
