### ISSUE TITLE
NameIDFormat Error

### ISSUE THREAD

**Issue by efanning** [catalyst/moodle-auth_saml2#228] opened 2018-03-15 14:02 UTC
**What happened?**
When attempting to create the Relying Party Trust on my Windows 2008 R2 server, I get the error message "The value 'NameIDFormat' must be an absolute URI" after entering the URL from the SAML2 plugin.

![nameidformat error](https://user-images.githubusercontent.com/35379527/37467754-771dfbb2-2837-11e8-8cc0-7200828b3b78.png)

**What you expected:**
I did not get this message a couple versions ago before I had to uninstall the plugin for other reasons and now getting this after reinstalling with updated version.  Is there something I'm not doing right?  Here is my metadata...

```
<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" entityID="https://mydomain/auth/saml2/sp/metadata.php">
<md:SPSSODescriptor protocolSupportEnumeration="urn:oasis:names:tc:SAML:1.1:protocol urn:oasis:names:tc:SAML:2.0:protocol" AuthnRequestsSigned="true">
<md:KeyDescriptor use="signing">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>
MIIEHzCCAwegAwIBAgIBADANBgkqhkiG9w0BAQUFADCBqTEPMA0GA1UEAwwGbW9vZGxlMQswCQYDVQQGEwJBVTEUMBIGA1UEBwwLbW9vZGxldmlsbGUxIzAhBgkqhkiG9w0BCQEWFGl0ZXF1aXBAYnJpbGplbnQuY29tMSwwKgYDVQQKDCNCcmlsamVudCBMZWFybmluZyBNYW5hZ2VtZW50IFN5c3RlbTEPMA0GA1UECAwGbW9vZGxlMQ8wDQYDVQQLDAZtb29kbGUwHhcNMTgwMzA3MTUyNzMzWhcNMjgwMzA0MTUyNzMzWjCBqTEPMA0GA1UEAwwGbW9vZGxlMQswCQYDVQQGEwJBVTEUMBIGA1UEBwwLbW9vZGxldmlsbGUxIzAhBgkqhkiG9w0BCQEWFGl0ZXF1aXBAYnJpbGplbnQuY29tMSwwKgYDVQQKDCNCcmlsamVudCBMZWFybmluZyBNYW5hZ2VtZW50IFN5c3RlbTEPMA0GA1UECAwGbW9vZGxlMQ8wDQYDVQQLDAZtb29kbGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDFvGbbQH2UMeVL41NV31ZDH71gq90tbCHK5k9XT0DNAPwr7aW1onTdTJkPJyY5CEKGecgWnDdb1PfQwXsfuX6D07dOvhVhUV//V8S5J22de9jKtaHNIPp5IzMOpQiV30JMxat5yO8sM5inYnrKmL6VUFReN49AYW7pPV1gpPBG3fr8HeByUdgdQKjtBeqmLQHOXx8AV8j+TtzzLCa2z6At7LEovxnAe5CBAqBO09ab1VNMh9keAPO4QSI/Z+WM4zHv/fwKLqJcgW+WHmP6zzU8uHpX1YmIbDVUSy19JpCW0IqYRKL4uKFFcF/d4qqYM/jnIo9TiKTeyI2p0lu1OhenAgMBAAGjUDBOMB0GA1UdDgQWBBQthZJbU4X5uiSPIczCskK+5ixRQTAfBgNVHSMEGDAWgBQthZJbU4X5uiSPIczCskK+5ixRQTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQAdmS1VVi0SQtRZp2WiRcTD/ywZidDIBKUyWSQtDXd2jwKP1hhI8ypzC8121CwdumxmnQrSAVGIRr7El79mTJjj58Nt7ru0xW3KHpIBMAfoRhHvAOQLtOByWaJolGrBaftgxnBer0BR/cMpiMbqk1DYOx0k/ZTBuPqy3hYxNjSljy+XoTIiAAO34DwSiXQW8T+yfmq8x0SeFlKrPmjVWErH35IDcgO4IpccH4faHEdwUzzJARhCLLA7Qws7SKsGYMzposjlmauh6BI83kIte7sG15xqU+Q6hR6j3vP9PL0cufaYxc+dEa03/rCgP0Xbl4py5ww/nYzj1bO5TgJQP9/2
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:KeyDescriptor use="encryption">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>
<ds:X509Certificate>
MIIEHzCCAwegAwIBAgIBADANBgkqhkiG9w0BAQUFADCBqTEPMA0GA1UEAwwGbW9vZGxlMQswCQYDVQQGEwJBVTEUMBIGA1UEBwwLbW9vZGxldmlsbGUxIzAhBgkqhkiG9w0BCQEWFGl0ZXF1aXBAYnJpbGplbnQuY29tMSwwKgYDVQQKDCNCcmlsamVudCBMZWFybmluZyBNYW5hZ2VtZW50IFN5c3RlbTEPMA0GA1UECAwGbW9vZGxlMQ8wDQYDVQQLDAZtb29kbGUwHhcNMTgwMzA3MTUyNzMzWhcNMjgwMzA0MTUyNzMzWjCBqTEPMA0GA1UEAwwGbW9vZGxlMQswCQYDVQQGEwJBVTEUMBIGA1UEBwwLbW9vZGxldmlsbGUxIzAhBgkqhkiG9w0BCQEWFGl0ZXF1aXBAYnJpbGplbnQuY29tMSwwKgYDVQQKDCNCcmlsamVudCBMZWFybmluZyBNYW5hZ2VtZW50IFN5c3RlbTEPMA0GA1UECAwGbW9vZGxlMQ8wDQYDVQQLDAZtb29kbGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDFvGbbQH2UMeVL41NV31ZDH71gq90tbCHK5k9XT0DNAPwr7aW1onTdTJkPJyY5CEKGecgWnDdb1PfQwXsfuX6D07dOvhVhUV//V8S5J22de9jKtaHNIPp5IzMOpQiV30JMxat5yO8sM5inYnrKmL6VUFReN49AYW7pPV1gpPBG3fr8HeByUdgdQKjtBeqmLQHOXx8AV8j+TtzzLCa2z6At7LEovxnAe5CBAqBO09ab1VNMh9keAPO4QSI/Z+WM4zHv/fwKLqJcgW+WHmP6zzU8uHpX1YmIbDVUSy19JpCW0IqYRKL4uKFFcF/d4qqYM/jnIo9TiKTeyI2p0lu1OhenAgMBAAGjUDBOMB0GA1UdDgQWBBQthZJbU4X5uiSPIczCskK+5ixRQTAfBgNVHSMEGDAWgBQthZJbU4X5uiSPIczCskK+5ixRQTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4IBAQAdmS1VVi0SQtRZp2WiRcTD/ywZidDIBKUyWSQtDXd2jwKP1hhI8ypzC8121CwdumxmnQrSAVGIRr7El79mTJjj58Nt7ru0xW3KHpIBMAfoRhHvAOQLtOByWaJolGrBaftgxnBer0BR/cMpiMbqk1DYOx0k/ZTBuPqy3hYxNjSljy+XoTIiAAO34DwSiXQW8T+yfmq8x0SeFlKrPmjVWErH35IDcgO4IpccH4faHEdwUzzJARhCLLA7Qws7SKsGYMzposjlmauh6BI83kIte7sG15xqU+Q6hR6j3vP9PL0cufaYxc+dEa03/rCgP0Xbl4py5ww/nYzj1bO5TgJQP9/2
</ds:X509Certificate>
</ds:X509Data>
</ds:KeyInfo>
</md:KeyDescriptor>
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://mydomain/auth/saml2/sp/saml2-logout.php/mydomain"/>
<md:NameIDFormat/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://mydomain/auth/saml2/sp/saml2-acs.php/mydomain" index="0"/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:browser-post" Location="https://mydomain/auth/saml2/sp/saml1-acs.php/mydomain" index="1"/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Artifact" Location="https://mydomain/auth/saml2/sp/saml2-acs.php/mydomain" index="2"/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:1.0:profiles:artifact-01" Location="https://mydomain/auth/saml2/sp/saml1-acs.php/mydomain" index="3"/>
</md:SPSSODescriptor>
<md:Organization>
<md:OrganizationName xml:lang="en">Briljent Learning Management System</md:OrganizationName>
<md:OrganizationDisplayName xml:lang="en">Briljent Learning Management System</md:OrganizationDisplayName>
<md:OrganizationURL xml:lang="en">https://mydomain</md:OrganizationURL>
</md:Organization>
<md:ContactPerson contactType="technical">
<md:GivenName>Admin</md:GivenName>
<md:SurName>User</md:SurName>
<md:EmailAddress>briljentlms@briljent.com</md:EmailAddress>
</md:ContactPerson>
</md:EntityDescriptor>
```

**Comment by roperto** [comment] 2018-03-15 22:35
Hi @efanning ,

We have clients using ADFS 3 without issues, I checked their metadata and they also have

`<md:NameIDFormat/>` (no value)

There is some work on the nameidpolicy in the branch https://github.com/catalyst/moodle-auth_saml2/tree/nameidpolicy but it still being tested before merging as stable, maybe you can try that code.

Please let me know if you can identify what is causing this so we can patch the plugin.

Thank you

Daniel

**Comment by fnook** [comment] 2018-03-16 11:02
I was just about to post the same issue. Our ADFS provider is getting the same issue when trying to add the metadata URL and also say they can't import manually due to the empty value in <md:NameIDFormat/>. 
Watching with interest.

**Comment by efanning** [comment] 2018-03-16 11:56
Thanks @roperto, I'll take a look at that branch, but I'm running ADFS 2.0, does that make a difference?

**Comment by roperto** [comment] 2018-03-18 22:14
Hi.

I am sorry to hear you are having problems. If it was working with the previous version, can you provide the metadata generated by the plugin before and the metadata generated now? If you can tweak manually the metadata to make it work, please let us know what changes you did.

The plugin should be compatible with ADFS 2 but at this point I don't know what the issue is.

Thank you.

**Comment by jtsafran** [comment] 2018-03-19 19:56
Hi all.  I am going to add a "me too" to this issue, with ADFS 3.0.  We tried to edit the metadata manually and remove the <md:NameIDFormat/> but it did not seem to make a difference.  Interestingly, this was with a client that we had a test site up with and the metadata looked exactly the same otherwise as far as format and tags.  I wish I would have kept a copy to do a diff on but we were moving quickly to get them up and running so just "downgraded" their live site to use the same version that was on the test site.  If I run into this again, I will make copies of both for further analysis.

**Comment by efanning** [comment] 2018-03-19 20:41
Unfortunately, I do not have the old XML file to be able to get this information to you.  However, I do have another ADFS set up for another connection and if look at that XML file, the NameIDFormat looks like this....

`<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:transient</md:NameIDFormat>`

I have searched for ways to change this without success.

**Comment by roperto** [comment] 2018-03-19 23:08
Thank you @jtsafran 

@efanning , if you get the metadata generated in your Moodle site, change that NameIDFormat line to that one that you pasted, and import into your ADFS does it work?

Maybe @nhoobin can help us as I think he has been working on something similar.

**Comment by efanning** [comment] 2018-03-22 19:58
Sorry for the late response, been caught up on something else, but I am happy to say that I have this working now.  I was able to download the XML file, edit it to add the proper NameIDFormat and then use the XML file to create my RPT, but still not able to using the URL.  Here's the NameIDFormat that I used.

`<md:NameIDFormat>urn:oasis:names:tc:SAML:2.0:nameid-format:persistent</md:NameIDFormat>`

I did do some research to see how to get it added via auth/saml2/sp/metadata.php but was very unsuccessful that way.  Hope this helps others.

**Comment by roperto** [comment] 2018-03-26 01:29
Hi all,

We just released v2018032600 which should fix that problem.

Please let us know if something is still not right.

Thank you

**Comment by efanning** [comment] 2018-03-26 12:05
Thank you for the update.  I installed the latest update and was able to make the change for the NameID but when I went to look at the metadata, it still was missing.

![2018-03-26 08_02_04-briljent learning management system_ administration_ plugins_ authentication_ sa](https://user-images.githubusercontent.com/35379527/37905282-588d63de-30cc-11e8-9155-92e1f0651461.png)

```
<md:SingleLogoutService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect" Location="https://lms.mydomain.com/auth/saml2/sp/saml2-logout.php/lms.mydomain.com"/>
<md:NameIDFormat/>
<md:AssertionConsumerService Binding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Location="https://lms.mydomain.com/auth/saml2/sp/saml2-acs.php/lms.mydomain.com" index="0"/>
```

**Comment by efanning** [comment] 2018-03-26 12:09
Well, I also logged off of my Moodle server and when to log back on, I get the following errors and will not let me log on via SAML anymore.  I get one error, click continue and then get the second error.

```
SAML2 exception: ACSPARAMS
SAML2 exception: Requester/InvalidNameIDPolicy
```

**Comment by efanning** [comment] 2018-03-26 19:14
I was able to finally get this working again.  I changed the NameIDPolicy in auth/saml2/config/authsources.php from `'NameIDPolicy' => $saml2auth->config->nameidpolicy` to null, but that still gave me errors.  I then changed it to `'NameIDPolicy' => 'urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified'` when then allowed me to reconnect via SAML.

**Comment by roperto** [comment] 2018-03-26 22:32
Hi @efanning , I am reopening this issue so we can investigate further.

**Comment by brendanheywood** [comment] 2020-02-21 13:38
This should be fixed now, when you update the settings the cached xml metadata is purged and rebuilt

**Closed by brendanheywood** 2020-02-21 13:38 UTC
Labels: bug
