### ISSUE TITLE
IdP initiated login flow not working (with OKTA configuration?)

### ISSUE THREAD

**Issue by matteodurini** [catalyst/moodle-auth_saml2#380] opened 2019-11-15 06:06 UTC
Hi, we are using auth_saml2 plugin version 2019022100 with totara. I was able to configure it and get it working if the connection is initiated from the homepage of the LMS. If i try to access from the OKTA page, i got the error reported in [this other issue](https://github.com/catalyst/moodle-auth_saml2/issues/324)
we followed the instructions from [this other thread](https://github.com/catalyst/moodle-auth_saml2/issues/362) but the error was still there, so we tried to remove the md5 validation as suggested at the end of the previous issue. now, we are landing to the homepage of totara without the login initiated. 
i followed the instructions provided on [this](https://github.com/catalyst/moodle-auth_saml2) page for OKTA, but i can't understand which certificate should i upload after enabling the Assertion Encryption
Thank you in advance.

**Comment by crystalllized** [comment] 2020-01-31 20:17
I'm having this same exact issue. SP initiated is successful, IdP initiated fails. Using version 2019110701 from the plugin directory. I first had to take a note from #387 and regenerate the certificate to even get SP-initiated to work, but now that's functional. I've tried clearing site caches and resaving settings many times as indicated in other issues but with no progress being made.

**Comment by brendanheywood** [comment] 2020-02-02 11:47
I'm not sure IdP initiated login flow has ever been tested, it may not have ever worked. I'd treat this as a feature request rather than a bug. As a workaround, you should in theory be able to deep link to the moodle login page including the 'idpalias' query param and a wantsurl for the final moodle destination page and then you'll be have a pseudo idp initiated link, but under the hood is an sp-first saml.

https://github.com/catalyst/moodle-auth_saml2/blob/master/auth.php#L468

I'd like to better understand the requirement for why you want or need IdP first flow, do you have moodle setup to work with many IdP's?

**Comment by matteodurini** [comment] 2020-02-03 07:22
hi brendanheywood, the idea to have the login initiated from the idp (OKTA) is related to the application gallery feature available in the OKTA user portal. From this page, users are able to see the assigned applications: in case of SAML applications, clicking on the icon of the app, the user will be redirected automatically to the application already logged-in. A temporary workaround with OKTA could be the creation of a separated application using the Bookmark template with the link generated in the LMS login screen by your plugin, hiding the SAML application itself to the end-user

**Comment by brendanheywood** [comment] 2020-02-07 04:38
Yeah I've had clients do that, the bookmark in OKTA is just a normal link, and the flow is SP first flow, but from the users point of view it's the same. Generally the only situation where I think you'd be forced to do IdP first flow is when the SP has multiple IdP's and the SP doesn't want to have an IdP chooser or IdP discovery in place. Even then, specially with moodle you can still work around that using the ?idp=xyz query param in the bookmark.

This isn't high on our radar and I am treating this as a feature request. If you or anyone wants to sponsor it please contact us and reference this issue:

https://www.catalyst-au.net/content/contact-us

**Comment by brendanheywood** [comment] 2020-03-05 04:26
I've gotten this working, will close this as duplicate of https://github.com/catalyst/moodle-auth_saml2/issues/105 and do comms there

**Closed by brendanheywood** 2020-03-05 04:26 UTC
Labels: enhancement
