### ISSUE TITLE
Locking user fields not working

### ISSUE THREAD

**Issue by jbollom** [catalyst/moodle-auth_saml2#43] opened 2016-09-07 03:08 UTC
It seems that setting fields to Lock value Locked under the data mapping has no affect and user are still able to update these details

**Comment by brendanheywood** [comment] 2016-09-07 03:48
What auth type are the users? The lockdown settings would only apply to saml2 users, if you are using the 'anyauth' option it's the locking settings of the other auth plugin which take effect.

If this isn't the issue then it's a real bug.

**Comment by jbollom** [comment] 2016-09-07 04:14
The users are saml2 auth types
I am aware that the auth type of the user does determine what lock settings are applied and as a work around we are looking to change our user accounts to a different auth type so that we can lock these fields down

**Comment by brendanheywood** [comment] 2016-09-07 04:20
Ok thanks for confirming that. I'll take a look when I get a chance. If you can provide a pull request then that's even better.

**Comment by shaispieler** [comment] 2016-09-15 08:28
Hi, 

We're facing the same problem with Moodle 3.1. Although the SAML2 fields first name, last name etc. are set to locked, users can still change them when editing their profile. 

As a temporary solution we've removed capability moodle/user:editownprofile in authenticated user but of-course this is only a temporary solution. 

Thanks,!

Shai

**Comment by nadavkav** [comment] 2016-09-15 10:26
Just now found out about it too, It's an issue for us too.

**Comment by AngelGroup** [comment] 2016-09-18 09:41
hi,
made 2 fixes to our **saml2/auth.php** file - fixing problems some might have been stumbled on:

- added an **override to is_internal method** (so when manually adding new saml2 user it won't require to fill the password field) - the method must **return false**

```
    function is_internal()
    {
        return false;
    }

```
- changed **the last line of the constructor** (added the **reading of 'auth/saml2' configuration** as well - so that the locked fields will take place)

```
        //$this->config = (object) array_merge($this->defaults, (array) get_config('auth_saml2') );
        $this->config = (object) array_merge($this->defaults, (array) get_config('auth_saml2'), (array) get_config('auth/saml2');

```

**Comment by brendanheywood** [comment] 2016-09-18 13:16
@nadavkav / @AngelGroup can you confirm you still have this issue on the latest master? (moodle directory may not be current) This *should* have been fixed in pull request https://github.com/CatalystIT-AU/moodle-auth_saml2/pull/32 a couple weeks ago

I've also just pushed the is_internal() fix thanks

**Comment by nadavkav** [comment] 2016-09-18 13:36
We are not using your latest code. (maybe we should!) and your fix looks like it should solve this issue.
I guess it this issue was a duplicate to that one. (can you mark it as so?)
I will have time to test it on our test system in about two days or so.
Maybe @AngelGroup can do it quicker ;-)

**Comment by brendanheywood** [comment] 2016-09-18 22:59
Thanks @nadavkav - the moodle directory generally should be no more than a month out of sync, I'll wait til this is confirmed good for both of you then update it.

**Comment by brendanheywood** [comment] 2020-02-21 13:43
This is fixed long ago

![image](https://user-images.githubusercontent.com/187449/75039220-4d1df980-550c-11ea-89b1-888f412fe5f8.png)

**Closed by brendanheywood** 2020-02-21 13:43 UTC
Labels: bug, duplicate
