### ISSUE TITLE
settings moodle 3.0

### ISSUE THREAD

**Issue by mjencabh** [catalyst/moodle-auth_saml2#119] opened 2017-07-03 10:39 UTC
I have installed SAML2 but i cant configure settings?
Whats wrong :(

**Comment by brendanheywood** [comment] 2017-07-04 02:44
hi @mjencabh I'll need some more details. Did you install the plugin via git from this repo or from the moodle plugins directory? There is a good change you have the wrong version for your moodle, there are two versions for before and after v3.3:

https://github.com/catalyst/moodle-auth_saml2/tree/MOODLE_UPTO32

https://github.com/catalyst/moodle-auth_saml2/tree/MOODLE_33PLUS

**Comment by SSSvensk** [comment] 2017-07-06 07:09
Hi, I have similiar issue. I downloaded this plugin yesterday from Moodle plugins directory and can't configure settings, in other words I can't see link "settings" in my authentication plugins page. More details in screenshot image. I have Moodle 3.3.
![github](https://user-images.githubusercontent.com/23612213/27899497-1ed5ee26-6233-11e7-8ea7-7de1e858f511.png)

**Comment by mjencabh** [comment] 2017-07-06 07:43
I Got it working! Just clone/downloade zip and then unzip! Aften that copy into filefolder auth an be sure to rename folder to saml2. Purge cache and then u should be running! There is something wrong when installing from moodle download :)

**Comment by SSSvensk** [comment] 2017-07-06 08:31
Okei, worked for me aswell! Now im facing errors when trying to pass IdP metadata, so it's printing out similiar warning messages than in issue #81.

**Comment by brendanheywood** [comment] 2017-07-10 01:46
@SSSvensk are you on windows and do you have all the php dependencies installed, eg mcrypt?

**Comment by SSSvensk** [comment] 2017-07-11 06:36
Yes, I have windows and all the dependencies. I was maybe a bit too hesitating in my previous message. To be more exact my problem is that I got this exception message when trying to generate metadata. 
`Poikkeus - authsources['localhost']: Unable to load certificate/public key from file "[dataroot]/saml2/localhost.crt` 
and my dataroot is declared: `$CFG->dataroot  = 'C:\\xampp\\moodledata';`

**Comment by brendanheywood** [comment] 2017-07-12 02:24
ok, all I can suggest without a more detailed look is to see if the directory is properly created with the right permissions and if that file is being generated correctly or not. If not then turn on full debugging in both moodle and in the saml plugin. It will most likely end up being something busted with the mcrypt libs, maybe they are not enabled in php?

**Comment by joeriks** [comment] 2017-09-14 10:10
I had the same problem on a linux (bitnami) installation in Azure. When I downloaded the 33plus as a zip and uploaded that one it worked (very easy to do). The moodle plugins directory unfortunately only has versions for up to 3.2 as far as I found.

**Comment by mattporritt** [comment] 2018-01-14 23:58
The Moodle Plugin directory now contains updated versions of the plugin. There are two versions available, one for Moodles up to and including V 3.2 and another one for Moodle versions 3.3 and above.

**Comment by roperto** [comment] 2018-03-08 05:41
We have now merged back a single version of the plugin for all Moodles and we cannot reproduce this anymore. Please reopen this issue if it is not solved for you.

**Closed by roperto** 2018-03-08 05:41 UTC
Labels: help wanted
