### ISSUE TITLE
Zip install fails on Windows IIS with corrupted_archive_structure

### ISSUE THREAD

**Issue by mwithheld** [catalyst/moodle-auth_saml2#597] opened 2021-08-25 02:48 UTC
**What happened?**

Install from zip fails on Windows IIS, probably due to the included .extlib folder name.

**To reproduce**

- Setup Moodle 3.9 on Windows IIS.
- Download the zip from the Moodle plugin page (https://moodle.org/plugins/auth_saml2).  In my case the version is https://moodle.org/plugins/download.php/24556/auth_saml2_moodle311_2021062900.zip

Stacktrace:

```
Install plugin from ZIP file

Debugging output enabled
ZIP C:\HostingSpaces\base_dir_here\data/temp/tool_installaddon/0d434400-e612-4877-85f5-5b803bc0617c/plugin.zip
Validating auth_saml2 ... 

core_plugin/corrupted_archive_structure

More information about this error

    


    Debug info:  Can not create directory

Error code: corrupted_archive_structure

$a contents: saml2/.extlib/simplesamlphp/vendor/phpfastcache/riak-client/src/Riak/Command/

    


    Stack trace:  

    line 544 of \lib\classes\update\code_manager.php: moodle_exception thrown
    line 195 of \lib\classes\update\code_manager.php: call to core\update\code_manager->move_extracted_plugin_files()
    line 1163 of \lib\classes\plugin_manager.php: call to core\update\code_manager->unzip_plugin_file()
    line 1351 of \lib\classes\plugin_manager.php: call to core_plugin_manager->unzip_plugin_file()
    line 2506 of \lib\upgradelib.php: call to core_plugin_manager->install_plugins()
    line 88 of \admin\tool\installaddon\index.php: call to upgrade_install_plugins()
```

I was able to get past the problem by FTP-ing the files up.
Probably would be an easy fix to rename that .extlib/ folder to something without a dot, e.g. vendor/

**Comment by danmarsden** [comment] 2021-08-25 03:43
At that point in the extraction the .extlib folder will already have been created on disk. It's more likely some other character or path inside the other folders within .extlib is the cause. We won't be removing the dot from the folder name as it is a convention used to include files in a plugin that should not be web accessible and it doesn't even look like the cause of your issue.

If you work out the real cause feel free to update the issue here, but I can't see us looking into this further as we do not host on windows or use the automatic plugin installer for adding plugins to a site.

Thanks!

**Comment by danmarsden** [comment] 2022-01-18 21:32
closing for now as cannot reproduce - but if you manage to isolate a problem that we can fix feel free to update the issue and we can take a look - it could also be a bug with the moodle core install plugin code rather than an issue in the saml2 plugin itself.

**Closed by danmarsden** 2022-01-18 21:32 UTC
