### ISSUE TITLE
Cannot login manually when Dual login = no

### ISSUE THREAD

**Issue by joncatalyst** [catalyst/moodle-auth_saml2#31] opened 2016-07-28 13:47 UTC
I have Moodle with SAML2 ( 2016041300) and Drupal as IdP. 
All works as expected with Dual login = yes.
I was trying to avoid the 'extra click' needed in Moodle (on SAML link login page to enact login).
Setting Dual login = no achieves this, but if I try to login as  admin - ie /login/index.php?saml=off (or saml=0), I see the login box, on Moodle, but after credentials are entered I get sent to Drupal login.
Loading Moodle page shows I'm still logged out.

**Comment by roperto** [comment] 2018-03-08 05:26
Hi Jon,

I am closing this as I cannot reproduce it and I've been using that feature without issues for a while.

Please reopen this one if you are still experiencing problems.

**Closed by roperto** 2018-03-08 05:26 UTC
Labels: bug
