### ISSUE TITLE
Inconsistent idp value

### ISSUE THREAD

**Issue by davosmith** [catalyst/moodle-auth_saml2#338] opened 2019-07-24 07:48 UTC
https://github.com/catalyst/moodle-auth_saml2/blob/04044eabec6bf0841d8f11f5a0da4abed53ae883/config/authsources.php#L43

When doing an unsolicited SSO direct from the IDP, with browser data cleared, it fails the first time, then succeeds the second time.

As far as I can tell, the reason it fails the first time is that when $SESSION->saml2idp is _not_ set, the 'idp' value in the config returned from the file I've indicated above is the **md5 hash** of the 'entityid' value. When $SESSION->saml2idp _is_ set, then the 'idp' value in the config is the raw 'entityid' value (not the md5 hash of that value). Please compare line 43, linked above, with line 49 in the same file.

This means that when the config is later retrieved and the entityid value is checked against the idp value, it fails to match and throws an error.

As far as I can tell, the correct fix would be to simply remove the md5() call from line 43.

**Comment by samchaffee** [comment] 2019-08-05 15:40
@davosmith, we're experiencing the same issue with unsolicited SSO direct from the IdP. Have you  been running the suggested patch since this was reported?

**Comment by davosmith** [comment] 2019-08-05 15:41
@samchaffee we've been running this patch on a UAT site, for testing purposes, but not yet deployed to a production site.

**Comment by samchaffee** [comment] 2019-08-05 15:44
Thanks, @davosmith, I appreciate it. We'll likely be putting this in place as well and I'll update this thread with any feedback we have if it's helpful for other folks.

**Comment by kristian-94** [comment] 2019-08-08 02:26
Thank you @davosmith for your comment here that helps to track down the issue. I'm able to reproduce the issue as you described, by simply clearing the browsers data and then trying to log in with saml. I'll be working on a patch to fix this issue.

**Comment by dmitriim** [comment] 2019-10-07 00:21
Hi all, 
Have you tried to resave config of the plugin? Does it fix the issue?
It seems like it's related to https://github.com/catalyst/moodle-auth_saml2/issues/362

**Comment by davosmith** [comment] 2019-10-09 20:15
Hi @dmitriim I'm not convinced that is the same issue - this isn't to do with the loading of saved config from the database or caches, but the settings that are saved temporarily in the $SESSION global. There is simply a mismatch between the idp identifier between two different places in the code where the relevant details in the $SESSION are initialised.

The fix I've already proposed is deployed and working for our customer on their UAT and production sites, so I'm not planning on doing any further investigation at the moment.

**Comment by brendanheywood** [comment] 2020-03-02 12:34
This should be fixed now

**Closed by brendanheywood** 2020-03-02 12:34 UTC
