### ISSUE TITLE
SAML2 exception: Responder

### ISSUE THREAD

**Issue by kathirr20** [catalyst/moodle-auth_saml2#254] opened 2018-05-08 07:52 UTC
saml authentication is happening successfully but while redirecting to my site. It is throwing this error. I could not able to find the cause. Please help.

SAML2 exception: Responder
More information about this error

I am following steps in https://moodle.org/plugins/view.php?plugin=auth_saml2&moodle_version=27

**Comment by danmarsden** [comment] 2018-05-08 08:59
this sounds like a duplicate of #195 - can you please make sure you are using the latest version of the saml2 plugin?

**Comment by brendanheywood** [comment] 2020-12-03 03:23
Closing this, please see https://github.com/catalyst/moodle-auth_saml2/issues/488

**Closed by brendanheywood** 2020-12-03 03:23 UTC
Labels: duplicate
