### ISSUE TITLE
Drag and Drop fails if session has ended (core bug?)

### ISSUE THREAD

**Issue by markvanlaar2221** [catalyst/moodle-auth_saml2#76] opened 2017-01-30 23:17 UTC
Drag and Drop a PDF into a topic gives this error "An error occurred whilst communicating with the server"

Logs:
[Tue Jan 31 09:26:21.654345 2017] [ssl:error] [pid 19773] [client 192.168.201.78:57593] AH02261: Re-negotiation handshake failed: Not accepted by client!?, referer: https://adfs.plc.nsw.edu.au/adfs/ls/?

Suggestions?

**Comment by brendanheywood** [comment] 2017-01-31 00:14
Super weird, I can only assume that the session has timed out, and the ajax handler for the file upload is trying to re-logic via saml. This feels like a core moodle bug, if there isn't a valid session it should alert the user. There may be a bug where saml is kicking in when it shouldn't, but then this too would also be a core bug where it is firing a login hook in the ajax handler when it shouldn't.

Can yo replicate this on demand by logging in, going to an upload form, killing the cookies and then dragging?

**Comment by markvanlaar2221** [comment] 2017-01-31 00:50
Yes, have logged in via ADFS, gone to course page, killed cookies, enabled edit mode, drag and drop a 200kb PDF and get the error. Have tested across courses, same issue. Strangely, when I "add an activity or resource" and select File, then name it and drag and drop into UPLOAD box it works. Seems to be an AJAX issue, specific to dragging into a course topic directly.
![dragfail](https://cloud.githubusercontent.com/assets/25443929/22448168/7b3e274e-e7ab-11e6-8db6-1373dd0fd986.GIF)

**Comment by roperto** [comment] 2018-03-08 05:28
Ajax calls will not work if session has expired, the redirect will not work as expected. I believe Moodle could show a warning when your session is about to or expired.

In any case I am closing this as there isn't much that can be done from saml2 perspective, please reopen it if you disagree.

**Comment by brendanheywood** [comment] 2018-03-14 23:13
@roperto I think this is actually a core bug, it should not be calling the pre_login_hook from ajax under any circumstances

**Comment by roperto** [comment] 2018-03-14 23:21
I'm reopening this until we can confirm the issue and open a Moodle tracker.

**Comment by brendanheywood** [comment] 2018-11-22 01:45
Logged this here:

https://tracker.moodle.org/browse/MDL-64160

**Comment by brendanheywood** [comment] 2020-02-21 13:01
I can't reproduce this with saml forced on, and killing cookies, I correctly get the normal session error popup:

![image](https://user-images.githubusercontent.com/187449/75036657-79367c00-5506-11ea-9c9a-06867819eb71.png)

**Closed by brendanheywood** 2020-02-21 13:01 UTC
Labels: bug
